StudyWithMentor/assignment_003_feedback/src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls'), name='todolist')
]

handler404 = PageNotFound.as_view()
handler500 = ServerErrorPage.as_view()

StudyWithMentor/assignment_003_feedback/src/todolist/urls.py
from django.urls import path
from .views import *

app_name = "todolist"

urlpatterns = [
    path('', WorkCardLV.as_view(), name='index'),
    path('work/', WorkCardLV.as_view(), name='work_list'),
    path('work/add/', WorkCreateView.as_view(), name='work_add'),
    path('work/<int:pk>/update/', WorkUpdateView.as_view(), name='work_update'),
    path('work/<int:pk>/delete/', WorkDeleteView.as_view(), name='work_delete'),
    path('work/<int:pk>/complete/', WorkCompleteView.as_view(), name='work_complete'),
    path('card/<int:fk>/add/', CardCreateView.as_view(), name='card_add'),
    path('card/<int:fk>/<int:pk>/update/', CardUpdateView.as_view(), name='card_update'),
    path('card/<int:fk>/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
    path('card/<int:fk>/<int:pk>/complete/', CardCompleteView.as_view(), name='card_complete'),
    # ToDo: Activity url settings
    # path('activity/<int:fk>/add/', ActivityCreateView.as_view(), name='card_add'),
    # path('activity/<int:fk>/<int:pk>/update/', ActivityUpdateView.as_view(), name='card_update'),
    # path('activity/<int:fk>/<int:pk>/delete/', ActivityDeleteView.as_view(), name='card_delete'),
]

StudyWithMentor/assignment_003_feedback/src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../../../favicon.ico">-->

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
    <link href="{% block extrastyle %}{% endblock %}" rel="stylesheet" type="text/css"/>
    <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <a href="{% url 'home' %}" class="text-white">
                  <strong>To Do List</strong>
                </a>
              <p class="text-muted">python Django Web framework - To Do List</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">계정</h4>
              <ul class="list-unstyled">
                <li><a href="{% url 'logout' %}" class="text-white">로그아웃</a></li>
                <li><a href="{% url 'password_change' %}" class="text-white">비밀번호 바꾸기</a></li>
              </ul>
              <h4 class="text-white">연락</h4>
              <ul class="list-unstyled">
                <li><a href="https://github.com/jangjichang" class="text-white">GitHub</a></li>
                <li><a href="https://www.facebook.com/jichang.jang.3" class="text-white">Like on Facebook</a></li>
                <li><a href="mailto:wlckd90@gmail.com" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          {% if user.is_authenticated %}
          <a href="{% url 'todolist:index' %}" class="navbar-brand d-flex align-items-center">
            <strong>To Do List</strong>
          </a>
          {% else %}
          <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center">
            <strong>To Do List</strong>
          </a>
          {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
    {% block jumbo %}

    {% endblock %}
      <div class="album py-5 bg-light">
        <div class="container">


            {% block content %}

            {% endblock %}

        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>Thanks to the <a href="https://getbootstrap.com/docs/4.0/getting-started/introduction/">Bootstrap</a> for free templates for everyone.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

StudyWithMentor/assignment_003_feedback/src/templates/home.html
{% extends 'base.html' %}
{% block title %}
home.html
{% endblock %}

{% block jumbo %}
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">할 일 을<br>안 하 면<br>새 로 운<br>우 주 가<br>탄 생 한 다</h1>
      <!--<p class="lead text-muted"></p>-->
      <hr class="my-4">
      <p>1. 원하는 대로 보드를 만들고 이름을 지정해주세요.</p>
      <p>2. 보드에 할 일을 추가하세요.</p>
      <p>3. 원하는대로 보드를 이동하면서 관리하세요.</p>
      <p>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" class="btn btn-primary my-2">로그아웃</a>
          <a href="{% url 'password_change' %}" class="btn btn-secondary my-2">비밀번호 바꾸기</a>
          <a href="{% url 'todolist:index' %}" class="btn btn-danger my-2">내 목록 확인하기</a>
        {% else %}
          <a href="{% url 'register' %}" class="btn btn-primary my-2">회원가입</a>
          <a href="{% url 'login' %}" class="btn btn-secondary my-2">로그인</a>
        {% endif %}
      </p>
    </div>
  </section>
{% endblock %}

{% block content %}
<div class="row">
<div class="col-md-12"><h3 class="text-center">To Do List 사용 예시<br>&nbsp;</h3></div>
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">할 일</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">탤런트 코드 50p까지 읽기</li>
        <li class="list-group-item">맛집 예약하기</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">진행중인 일</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">여행 계획 세우기</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">끝난 일</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">미용실 예약하기</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">사이드 프로젝트</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">도메인 등록하기</li>
      <li class="list-group-item">aws s3 액세스 설정하기</li>
      <li class="list-group-item">github repository 생성하기</li>
      <li class="list-group-item">일요일 마포에서 회의</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">Django 공부하기</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Django 실전편 15장 공부하기</li>
      <li class="list-group-item">배프의 오지랖 파이썬 웹 프로그래밍 1장 공부하기</li>
      <li class="list-group-item">To Do List 앱 만들기</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">1년에 12권 책 읽기</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">1월 - 프로그래머의 길, 멘토에게 묻다.</li>
      <li class="list-group-item">2월 - 어떻게 살 것인가?</li>
      <li class="list-group-item">3월 - 탤런트 코드</li>
      <li class="list-group-item">4월 - 파이썬 웹 프로그래밍 실전편</li>
      <li class="list-group-item">5월 - 1만 시간의 재발견</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>

<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <div class="card-body">
      <h5 class="card-title">멘토링 프로젝트</h5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">4월 오프라인 모임 발표 준비하기</li>
      <li class="list-group-item">To Do List 앱 만들기</li>
      <li class="list-group-item">현금 영수증 신청하기</li>
    </ul>
      <div class="d-flex justify-content-between align-items-center">
        <div class="card-body">
          <a href="#" class="card-link">자세히 보기</a>
          <a href="#" class="card-link">수정하기</a>
        </div>
      </div>
    </div>
</div>
</div>
{% endblock %}