StudyWithMentor/assignment_003_feedback/src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls'), name='todolist')
]

handler404 = PageNotFound.as_view()
handler500 = ServerErrorPage.as_view()

StudyWithMentor/assignment_003_feedback/src/todolist/urls.py
from django.urls import path
from .views import *

app_name = "todolist"

urlpatterns = [
    path('', WorkCardLV.as_view(), name='index'),
    path('work/', WorkCardLV.as_view(), name='work_list'),
    path('work/add/', WorkCreateView.as_view(), name='work_add'),
    path('work/<int:pk>/update/', WorkUpdateView.as_view(), name='work_update'),
    path('work/<int:pk>/delete/', WorkDeleteView.as_view(), name='work_delete'),
    path('work/<int:pk>/complete/', WorkCompleteView.as_view(), name='work_complete'),
    path('card/<int:fk>/add/', CardCreateView.as_view(), name='card_add'),
    path('card/<int:fk>/<int:pk>/update/', CardUpdateView.as_view(), name='card_update'),
    path('card/<int:fk>/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
    path('card/<int:fk>/<int:pk>/complete/', CardCompleteView.as_view(), name='card_complete'),
    # ToDo: Activity url settings
    # path('activity/<int:fk>/add/', ActivityCreateView.as_view(), name='card_add'),
    # path('activity/<int:fk>/<int:pk>/update/', ActivityUpdateView.as_view(), name='card_update'),
    # path('activity/<int:fk>/<int:pk>/delete/', ActivityDeleteView.as_view(), name='card_delete'),
]

StudyWithMentor/assignment_003_feedback/src/todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Work(models.Model):
    name = models.CharField(max_length=50, verbose_name="목록 이름")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)
    done = models.BooleanField(default=False)

    class Meta:
        ordering = ['-modify_date', ]

    def __str__(self):
        return self.name


class Card(models.Model):
    name = models.CharField(max_length=50, verbose_name="할 일")
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)
    done = models.BooleanField(default=False)

    description = models.CharField(max_length=50, blank=True, verbose_name="간단한 설명")
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    deadline = models.DateField(blank=True, null=True, verbose_name="마감 기한")

    class Meta:
        ordering = ['-modify_date', ]

    def __str__(self):
        return self.name

    # ToDo: view 작성하고 작성하기
    def get_absolute_url(self):
        return reverse('todolist:card_detail', args=(self.id,))


class Activity(models.Model):
    description = models.CharField(max_length=100, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)

    card = models.ForeignKey(Card, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-modify_date', ]

    def __str__(self):
        return self.description

StudyWithMentor/assignment_003_feedback/src/todolist/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import Work, Card, Activity


class DateInput(forms.DateInput):
    input_type = 'date'


class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['name', 'description', 'deadline']
        widgets = {
            'deadline': DateInput(),
        }


CardInlineFormSet = inlineformset_factory(
                        Work,
                        Card,
                        form=CardForm,
                        can_delete=False,
                        extra=1)

StudyWithMentor/assignment_003_feedback/src/todolist/views.py
from django.shortcuts import redirect, render_to_response
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, Http404

from mysite.views import LoginRequiredMixin
from .models import Work, Card, Activity
from .forms import CardForm, CardInlineFormSet

# Create your views here.


class WorkCardLV(LoginRequiredMixin, ListView):
    model = Work

    def get_queryset(self):
        return Work.objects.filter(owner=self.request.user)


class WorkCreateView(LoginRequiredMixin, CreateView):
    model = Work
    fields = ['name',]
    success_url = reverse_lazy('todolist:index')

    def get_context_data(self, **kwargs):
        context = super(WorkCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = CardInlineFormSet(self.request.POST)
        else:
            context['formset'] = CardInlineFormSet()
        return context

    # form은 work, formset은 card
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for cardform in formset:
            cardform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('todolist:index')
        else:
            return self.render_to_response(self.get_context_data(form=form))


class WorkUpdateView(LoginRequiredMixin, UpdateView):
    model = Work
    fields = ['name', ]
    success_url = reverse_lazy('todolist:index')

    def get_queryset(self):
        work_update_obj = Work.objects.filter(owner=self.request.user).filter(id=self.kwargs['pk'])
        return work_update_obj

    def get_context_data(self, **kwargs):
        context = super(WorkUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = CardInlineFormSet(self.request.POST, instance=self.object)
        else:
            context['formset'] = CardInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        for cardform in formset:
            cardform.instance.owner = self.request.user
            cardform.instance.work = Work.objects.get(id=self.kwargs['pk'])
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect('todolist:index')
        else:
            return self.render_to_response(self.get_context_data(form=form))


class WorkDeleteView(LoginRequiredMixin, DeleteView):
    model = Work
    success_url = reverse_lazy('todolist:index')

    def get_queryset(self):
        work_delete_obj = Work.objects.filter(owner=self.request.user).filter(id=self.kwargs['pk'])
        return work_delete_obj


class WorkCompleteView(LoginRequiredMixin, DeleteView):
    model = Work

    def get_queryset(self):
        work_complete_obj = Work.objects.filter(owner=self.request.user).filter(id=self.kwargs['pk'])
        return work_complete_obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        object.owner.score += 1
        success_url = reverse_lazy('todolist:index')
        self.object.delete()
        return HttpResponseRedirect(success_url)


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('todolist:index')

    def get_queryset(self):
        if Work.object.filter(id=self.kwargs['fk']) != self.request.user:


    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.work = Work.objects.get(id=self.kwargs['fk'])
        return super(CardCreateView, self).form_valid(form)


class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('todolist:index')

    def get_context_data(self, **kwargs):
        if self.request.user != Card.objects.get(id=self.kwargs['pk']).owner:
            raise Http404
        else:
            context = super(CardUpdateView, self).get_context_data(**kwargs)
            return context


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = Card
    success_url = reverse_lazy('todolist:index')

    def get_context_data(self, **kwargs):
        if self.request.user != Card.objects.get(id=self.kwargs['pk']).owner:
            raise Http404
        else:
            context = super(CardDeleteView, self).get_context_data(**kwargs)
            return context


class CardCompleteView(LoginRequiredMixin, DeleteView):
    pass

# ToDo: Activity 기능 추가하기
# class ActivityCreateView(LoginRequiredMixin, CreateView):
#     model = Activity
# 
# 
# class ActivityUpdateView(LoginRequiredMixin, UpdateView):
#     model = Activity
# 
# 
# class ActivityDeleteView(LoginRequiredMixin, DeleteView):
#     model = Activity

StudyWithMentor/assignment_003_feedback/src/todolist/templates/todolist/card_confirm_delete.html
{% extends "base.html" %}
{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<div class="col-md-4 col-sm-4">
    <div class="card mb-4 box-shadow">
        <form action="." method="post">{% csrf_token %}
            <div class="card-body">
                <h5 class="card-title">"{{ object }}"를 완료/삭제하겠습니까?</h5>
            </div>
            <ul class="list-group list-group-flush">
                <input type="submit" class="btn btn-danger" value="완료/삭제하기"/>
            </ul>
        </form>
    </div>
</div>
{% endblock %}

StudyWithMentor/assignment_003_feedback/src/todolist/templates/todolist/card_form.html
<!--todo: crispy로 form 변경하기-->
{% extends "base.html" %}

{% block title %}card_form.html{% endblock %}

{% load staticfiles %}

{% load crispy_forms_tags %}

{% block content %}
<form action="." method="post">{% csrf_token %}
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5 class="card-title">할 일을 추가하거나 수정하세요.</h5>
                </div>
                <ul class="list-group list-group-flush">
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary" value="저장하기"/>
                    {% if object %}
                    <a class="btn btn-danger" href="{% url 'todolist:card_delete' object.work.id object.id %}">완료/삭제하기</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</form>
{% endblock %}

StudyWithMentor/assignment_003_feedback/src/todolist/templates/todolist/work_confirm_delete.html
{% extends "base.html" %}
{% block title %}worklist_confirm_delete.html{% endblock %}

{% block content %}
<div class="col-md-4 col-sm-4">
    <div class="card mb-4 box-shadow">
        <form action="." method="post">{% csrf_token %}
            <div class="card-body">
                <h5 class="card-title">"{{ object }}"를 완료/삭제하겠습니까?</h5>
            </div>
            <ul class="list-group list-group-flush">
                <input type="submit" class="btn btn-danger" value="완료/삭제하기"/>
            </ul>
        </form>
    </div>
</div>
{% endblock %}

StudyWithMentor/assignment_003_feedback/src/todolist/templates/todolist/work_form.html
{% extends "base.html" %}

{% block title %}work_form.html{% endblock %}

{% load staticfiles %}

{% load crispy_forms_tags %}


{% block content %}
<form action="." method="post">{% csrf_token %}
    <div class="row">
        <div class="col-md-4 col-sm-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5 class="card-title">목록을 생성하거나 추가하세요.</h5>
                </div>
                <ul class="list-group list-group-flush">
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-primary" value="저장하기"/>
                    {% if object %}
                    <a class="btn btn-danger" href="{% url 'todolist:work_delete' object.id %}">완료/삭제하기</a>
                    {% endif %}
                </ul>
            </div>
        </div>
<!--ToDo: 버튼 클릭 시 입력 폼 생성, 삭제되는 기능 구현-->
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.id }}
            <div class="col-md-4 col-sm-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">할 일을 생성하거나 추가하세요.</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        {{ form|crispy }}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
</form>
{% endblock %}

StudyWithMentor/assignment_003_feedback/src/todolist/templates/todolist/work_list.html
{% extends "base.html" %}
{% block title %}work_list{% endblock %}

{% load staticfiles %}

{% block content %}
<div class="row">
    <!--object_list가 있으면 work 출력 후 마지막에 +Add another work 출력-->
    {% if object_list %}
        {% for work in object_list %}
            <div class="col-md-4 col-sm-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title"><a class="text-dark" href="{% url 'todolist:work_update' work.id %}">{{ work.name }}</a></h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% if work.card_set.all %}
                            <!--work에 card가 있으면 card 출력 후 마지막에 +Add another card 출력 -->
                            {% for card in work.card_set.all %}
                                <a class="text-dark" href="{% url 'todolist:card_update' work.id card.id %}">
                                <li class="list-group-item"><p>{{ card.name }}</p></a>
                                    {% if card.description %}
                                    <button type="button" class="btn btn-info"><a class="text-white" href="{% url 'todolist:card_update' work.id card.id %}">설명</a></button>
                                    {% endif %}
                                    {% if card.deadline %}
                                        <button type="button" class="btn btn-warning"><a class="text-white" href="{% url 'todolist:card_update' work.id card.id %}">
                                            {{ card.deadline|date:"M j"}}일</a></button>
                                    {% endif %}
                                    <button type="button" class="btn btn-danger"><a class="text-white" href="{% url 'todolist:card_delete' work.id card.id %}">완료/삭제하기</a></button>
                                </li>
                                {% if forloop.last %}
                                <!--card가 있을 때 마지막 card 출력 후 +Add another card 출력-->
                                <li class="list-group-item"><a href="{% url 'todolist:card_add' work.id %}">+할 일 카드 추가하기</a></li>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <!--work에 card가 없으면 +Add a card 출력-->
                            <li class="list-group-item"><a href="{% url 'todolist:card_add' work.id %}">+할 일 카드 추가하기</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            {% if forloop.last %}
            <!--object_list가 있을 때 마지막 work 출력 후 +Add another work 출력-->
                <div class="col-md-4 col-sm-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'todolist:work_add' %}">+새로운 목록 추가하기</a></h5>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <!--object_list가 없으면 +Add a work 출력-->
        <div class="col-md-4 col-sm-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'todolist:work_add' %}">+새로운 목록 추가하기</a></h5>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}