StudyWithMentor/assignment_003/src/todoapp/urls.py
from django.contrib import admin
from .views import HomeRedirectView
from django.urls import include, path
from .views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    # ToDo: Home 화면 만들기
    path('', HomeRedirectView.as_view()),
    path('todo/', include('workmanagement.urls')),
    # 장고의 인증 URLconf를 가져와서 사용함
    path('accounts/', include('django.contrib.auth.urls')),
    # 계정 생성(가입) 처리를 하는 URL
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done', UserCreateDoneTV.as_view(), name='register_done'),
]

StudyWithMentor/assignment_003/src/workmanagement/urls.py
from django.urls import path
from .views import *

app_name = "workmanagement"

urlpatterns = [
    path('', ListCardLV.as_view(), name='index'),
    path('worklist/', ListCardLV.as_view(), name='worklist_show'),
    path('worklist/add/', ListCreateView.as_view(), name='worklist_add'),
    path('worklist/<int:pk>/update/', ListUpdateView.as_view(), name='worklist_update'),
    path('worklist/<int:pk>/delete/', ListDeleteView.as_view(), name='worklist_delete'),
    path('card/<int:fk>/add/', CardCreateView.as_view(), name='card_add'),
    path('card/<int:fk>/<int:pk>/update/', CardUpdateView.as_view(), name='card_update'),
    path('card/<int:fk>/<int:pk>/delete/', CardDeleteView.as_view(), name='card_delete'),
]

StudyWithMentor/assignment_003/src/workmanagement/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class WorkList(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Card(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=50, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    worklist = models.ForeignKey(WorkList, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)
    deadline_date = models.DateField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('workmanagement:card_detail', args=(self.id,))


class Activity(models.Model):
    description = models.CharField(max_length=100, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    create_date = models.DateField(auto_now_add=True)
    modify_date = models.DateField(auto_now=True)

    def __str__(self):
        if len(self.description) >= 10:
            return self.description[:10] + "..."
        return self.description

StudyWithMentor/assignment_003/src/workmanagement/forms.py
from django import forms
from django.forms import ModelForm
from .models import WorkList, Card, Activity
from django.forms.models import inlineformset_factory

class DateInput(forms.DateInput):
    input_type = 'date'


class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['name', 'description', 'deadline_date']
        widgets = {
            'deadline_date': DateInput(),
        }

StudyWithMentor/assignment_003/src/todoapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# login_required() 함수를 임포트합니다. 데코레이터로 사용되는 함수로, 일반 함수에 적용합니다.
# 기능은 사용자가 로그인했는지를 확인해 로그인한 경우는 원래 함수를 실행하고,
# 로그인이 되지 않은 경우는 로그인 페이지로 리다이렉트시킵니다.
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView

from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

class HomeRedirectView(RedirectView):
    pattern_name = 'workmanagement:index'


# TODO: 나중에 HomeView 만들어서 프로젝트 소개 작성하기
# class HomeView(TemplateView):
#     template_name = 'home.html'


# login_required()함수는 함수에만 적용할 수 있으므로, 클래스형 뷰에서는
# 이 LoginRequiredMixin 클래스를 상속받아 사용하면 login_required() 데코레이터 기능을 제공할 수 있습니다.
class LoginRequiredMixin:
    # as_view() 메소드를 인스턴스 메소드가 아니라 클래스 메소드로 정의합니다.
    @classmethod
    # as_view() 메소드는 항상 클래스 메소드로 정의해야합니다.
    # super() 메소드에 의해 LoginRequiredMixin의 상위 클래스에 있는 as_view() 메소드가 view 변수에 할당됩니다.
    def as_view(cls, **initkwargs):
        # view 변수, 즉 LoginRequiredMixin의 상위 클래스에 있는 as_view() 메소드에
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        # login_required() 기능을 적용하고 그 결과를 반환합니다.
        return login_required(view)

    # 위 소스는 파이썬의 다중 상속 문법을 이해해야 정확히 파악할 수 있습니다.
    # 간단히 정리하면 LoginRequiredMixin 클래스를 상속받는 클래스의 as_view() 메소드를 호출하면,
    # 다중 상속 구조의 메소드를 호출하는 순서에 의해 View 클래스의 as_view() 메소드에 login_required() 기능이 적용됩니다.

    # 클래스형 뷰에 데코레이터 적용 방법
    # 원래 데코레이터 기능은 함수에 적용되어 그 함수의 기능을 확장하는 역할을 합니다.
    # 만일 클래스에 데코레이터 기능을 적용하려면 약간의 추가 작업을 해야 합니다.
    # 앞에서 설명한 LoginRequiredMixin 클래스를 사용해 상속 방식으로 데코레이터 기능을 적용할 수 있습니다.
    # 그 외에도 URLconf 정의에 데코레이터 함수를 적용하는 방법과 dispatch() 메소드에 데코레이터 함수를 적용하는 방법이 있습니다.


# User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

StudyWithMentor/assignment_003/src/workmanagement/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy

from todoapp.views import LoginRequiredMixin
from .models import WorkList, Card, Activity
from .forms import CardForm

# Create your views here.

# To Do: 로그인한 사용자가 소유한 레코드만 넘기도록 추가하기


class ListCardLV(LoginRequiredMixin, ListView):
    model = WorkList

    def get_queryset(self):
        return WorkList.objects.filter(owner=self.request.user)


class ListCreateView(LoginRequiredMixin, CreateView):
    model = WorkList
    fields = ['name']
    success_url = reverse_lazy('workmanagement:worklist_show')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ListCreateView, self).form_valid(form)


class ListUpdateView(LoginRequiredMixin, UpdateView):
    model = WorkList
    fields = ['name']
    success_url = reverse_lazy('workmanagement:worklist_show')


class ListDeleteView(LoginRequiredMixin, DeleteView):
    model = WorkList
    success_url = reverse_lazy('workmanagement:worklist_show')


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('workmanagement:worklist_show')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.worklist = WorkList.objects.get(id=self.kwargs['fk'])
        return super(CardCreateView, self).form_valid(form)


class CardUpdateView(LoginRequiredMixin, UpdateView):
    model = Card
    form_class = CardForm
    success_url = reverse_lazy('workmanagement:worklist_show')


class CardDeleteView(LoginRequiredMixin, DeleteView):
    model = Card
    success_url = reverse_lazy('workmanagement:worklist_show')

StudyWithMentor/assignment_003/src/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}To Do App{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-custom">
      <!-- Brand -->
        <a class="navbar-brand" href="{% url 'workmanagement:index' %}"><h1>할 일을 안하면 <br>&nbsp;&nbsp;새로운 우주가 탄생한다.</h1></a>
        <ul class="navbar-nav">
        {% if user.is_active %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">로그아웃하고<br>지구로 돌아가기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'password_change' %}">비밀번호 바꾸기</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">로그인하고<br>우주를 만들어보자</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">회원가입하고<br>우주를 만들어보자</a>
          </li>
        {% endif %}
        </ul>
    </nav>
    {% block content %} {% endblock %}
    {% block footer %} {% endblock %}
</body>
</html>

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/card_confirm_delete.html
{% extends "base.html" %}
{% block title %}album_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">
    <form action="." method="post"> {% csrf_token %}
        <h3>정말로 "{{ object }}"를 삭제 할거에요?</h3>
        <input type="submit" value="삭제하기"/>
    </form>
</div>
{% endblock %}

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/card_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/card_form.html
<!--todo: crispy로 form 변경하기-->
{% extends "base.html" %}

{% block title %}worklist_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "workmanagement/workmanagement.css" %}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="container">
    <div class="row">
        <div class="col-8 col-md-3">
            <div class="p-2 worklist">
                <div class="p-2 worklist-title">
                    <form action="." method="post">{% csrf_token %}
                        {% if form.errors %}
                        <p class="errornote">Wrong! Please correct the error(s) below.</p>
                        {% endif %}

                        <p>Create or Update your card.</p>

                        <fieldset class="aligned">
                            <div class="form-row">
                                {{ form|crispy }}
                            </div>
                        </fieldset>
                        <div class="form-row">
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                        <script type="text/javascript">document.getElementById('id_name').focus();</script>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/test_worklist_list.html
{% block content %}
<div class="d-flex flex-nowrap">
    {% if object_list %}
    <!--object_list가 있으면 worklist 출력 후 마지막에 Add another worlist 출력-->
        {% for worklist in object_list %}
            <div class="col-8 col-md-3">
                <div class="p-2 worklist">
                    <div class="p-2 worklist-title">
                        {{ worklist.name }}
                        <button type="button" class="btn float-right see-more">...</button>
                    </div>
                    {% if worklist.card_set.all %}
                    <!--worklist에 card가 있으면 card 출력 후 마지막에 Add another card 출력 -->
                    {% for card in worklist.card_set.all %}
                            <div class="p-2 mycard-content">
                                <div class="p-2 mycard-title">
                                    {{ card.name }}
                                </div>
                                <div class="p-2 mycard-status">
                                    <i>card status</i>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                    <!--worklist에 card가 없으면 Add a card 출력-->
                    <div class="p-2 mycard-content">
                            <div class="p-2 mycard-title">
                                +Add a card
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% if forloop.last %}
            <!--object_list가 있을 때 마지막 worklist 출력 후 Add another worklist 출력-->
                <div class="col-8 col-md-3">
                    <div class="p-2 worklist">
                        <div class="p-2 worklist-title">
                            +Add another worklist
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <!--object_list가 없으면 worklist 생성 버튼만 출력-->
    <div class="col-8 col-md-3">
        <div class="p-2 worklist">
            <div class="p-2 worklist-title">
                +Add a worklist
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/worklist_confirm_delete.html
{% extends "base.html" %}
{% block title %}worklist_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">
    <form action="." method="post"> {% csrf_token %}
        <h3>정말로 "{{ object }}"를 삭제 할거에요?</h3>
        <input type="submit" value="삭제하기"/>
    </form>
</div>
{% endblock %}

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/worklist_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/worklist_form.html
{% extends "base.html" %}

{% block title %}worklist_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "workmanagement/workmanagement.css" %}{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="container">
    <div class="row">
        <div class="col-8 col-md-3">
            <div class="p-2 worklist">
                <div class="p-2 worklist-title">
                    <form action="." method="post">{% csrf_token %}
                        {% if form.errors %}
                        <p class="errornote">Wrong! Please correct the error(s) below.</p>
                        {% endif %}

                        <p>Create or Update your worklist.</p>

                        <fieldset class="aligned">
                            <div class="form-row">
                                {{ form|crispy }}
                            </div>
                        </fieldset>
                        <div class="form-row">
                            <input type="submit" class="btn btn-success" value="Submit"/>
                        </div>
                        <script type="text/javascript">document.getElementById('id_name').focus();</script>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

StudyWithMentor/assignment_003/src/workmanagement/templates/workmanagement/worklist_list.html
{% extends "base.html" %}
{% block title %}worklist_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "workmanagement/workmanagement.css" %}{% endblock %}

{% block content %}
<div class="d-flex flex-nowrap">
    {% if object_list %}
    <!--object_list가 있으면 worklist 출력 후 마지막에 +Add another worlist 출력-->
        {% for worklist in object_list %}
            <div class="col-8 col-md-3">
                <div class="p-2 worklist">
                    <a href="{% url 'workmanagement:worklist_update' worklist.id %}">
                        <div class="p-2 worklist-title">
                            {{ worklist.name }}
                        </div>
                    </a>
                    <a href="{% url 'workmanagement:worklist_delete' worklist.id %}">
                        <div>
                            삭제하기
                        </div>
                    </a>
                    {% if worklist.card_set.all %}
                    <!--worklist에 card가 있으면 card 출력 후 마지막에 +Add another card 출력 -->
                        {% for card in worklist.card_set.all %}
                            <div class="p-2 mycard-content">
                                <a href="{% url 'workmanagement:card_update' worklist.id card.id %}">
                                    <div class="p-2 mycard-title">
                                        {{ card.name }}
                                    </div>
                                    <div class="p-2 mycard-status">
                                        {% if card.description %}
                                            <button type="button" class="btn btn-info">Info</button>
                                        {% endif %}
                                        {% if card.deadline_date %}
                                            <button type="button" class="btn btn-danger">
                                                {{ card.deadline_date|date:"M j"}}</button>
                                        {% endif %}
                                    </div>
                                </a>
                                <a href="{% url 'workmanagement:card_delete' worklist.id card.id %}">삭제하기</a>
                            </div>
                            {% if forloop.last %}
                            <!--card가 있을 때 마지막 card 출력 후 +Add another card 출력-->
                            <div class="p-2 mycard-content">
                                <a href="{% url 'workmanagement:card_add' worklist.id %}">
                                <div class="p-2 mycard-title">
                                    +Add another card
                                </div>
                                </a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                    <!--worklist에 card가 없으면 +Add a card 출력-->
                        <div class="p-2 mycard-content">
                            <a href="{% url 'workmanagement:card_add' worklist.id %}">
                            <div class="p-2 mycard-title">
                                +Add a card
                            </div>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% if forloop.last %}
            <!--object_list가 있을 때 마지막 worklist 출력 후 +Add another worklist 출력-->
                <div class="col-8 col-md-3">
                    <div class="p-2 worklist">
                        <a href="{% url 'workmanagement:worklist_add' %}">
                            <div class="p-2 worklist-title">
                                +Add another worklist
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <!--object_list가 없으면 +Add a worklist 출력-->
    <div class="col-8 col-md-3">
        <div class="p-2 worklist">
            <a href="{% url 'workmanagement:worklist_add' %}">
                <div class="p-2 worklist-title">
                    +Add a worklist
                </div>
            </a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}